#!/bin/sh

monitor-sensor | mawk -W interactive '/Accelerometer orientation changed:/ { print $NF; fflush();}' | while read -r line
do
    printf "Accelerometer: %s\n" "$line"

    # If we have external monitor connected, do not rotate
    nscreens=$(kscreen-console outputs | grep -c "^Id:")
    if [ "$nscreens" != 1 ]
    then
        printf "But we have a second screen, so we don't rotate.\n"
        line=normal
    fi

    # Set the actions to be taken for each possible orientation
    case "$line" in
        normal)
            kscreen-doctor output.1.rotation.normal
            ;;
        bottom-up)
            kscreen-doctor output.1.rotation.inverted
            ;;
        right-up)
            kscreen-doctor output.1.rotation.right
            ;;
        left-up)
            kscreen-doctor output.1.rotation.left
            ;;
    esac
done

exit 0
