#!/bin/sh

monitor-sensor --accel | sed -n -u 's| *Accelerometer orientation changed: \(.*\)|\1|p' | while read -r orientation; do
    printf "Orientation: '%s'\n" "$orientation"

    screen=""
    for l in $(kscreen-doctor -o | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' | sed -n 's/Output: \([^ ]*\) [^ ]* enabled.*/\1/p'); do
        if [ "$screen" = "" ]; then
            screen="$l"
        else
            screen="MULTIPLE"
        fi
    done

    printf "Screen: '%s'\n" "$screen"

    if [ "$screen" = "" ]; then
        printf "Doing nothing because no screen was detected.\n"
        continue
    fi

    if [ "$screen" = "MULTIPLE" ]; then
        printf "Doing nothing because multiple screens were detected.\n"
        continue
    fi

    if [ "$orientation" = "bottom-up" ]; then
        orientation="inverted"
    elif [ "$orientation" = "right-up" ]; then
        orientation="right"
    elif [ "$orientation" = "left-up" ]; then
        orientation="left"
    fi

    kscreen-doctor "output.$screen.orientation.$orientation"
done

exit 0
