#!/bin/sh

monitor-sensor --accel | sed -n 's| *Accelerometer orientation changed: \(.*\)|\1|p' | while read -r line
do
    ## This doesn't work. `kscreen-console` crashes for me with a core dump -__-
    # If we have external monitor connected, do not rotate
    # nscreens=$(kscreen-console outputs | grep -c "^Id:")
    # if [ "$nscreens" != 1 ]
    # then
    #     printf "But we have a second screen, so we don't rotate.\n"
    #     line=normal
    # fi

    case "$line" in
        normal)
            kscreen-doctor output.1.rotation.normal
            ;;
        bottom-up)
            kscreen-doctor output.1.rotation.inverted
            ;;
        right-up)
            kscreen-doctor output.1.rotation.right
            ;;
        left-up)
            kscreen-doctor output.1.rotation.left
            ;;
    esac
done

exit 0
